# GLOBAL STUFF
experiment_id: StableCascadePro
checkpoint_path: ./models/stage_c_bf16.safetensors
output_path: ./stable_cc_pro_output
model_version: 3.6B

# WandB
wandb_project: StableCascadePro
wandb_entity: nbardy-facet

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 32
image_size: 1536
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 4
updates: 10000
backup_every: 1000
save_every: 100
warmup_updates: 1
# use_fsdp: True -> FSDP doesn't work at the moment for LoRA
use_fsdp: False

# GDF
# adaptive_loss_weight: True

# LoRA specific
module_filters: ['.attn']
rank: 4
train_tokens:
  # None: TODO[ Traing a text encoder LORA instead]
  # - ['^snail', null] # token starts with "snail" -> "snail" & "snails", don't need to be reinitialized
  # - ['[fernando]', '^dog</w>'] # custom token [snail], initialize as avg of snail & snails
  # - ['[HQ]', 'photorealism'] # custom token [snail], initialize as avg of snail & snails


# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

huggingface_dataset_path:
  # Small amount of curated top synthetic images
  - facet/MJ_v6_HQ

  # Large Gen slightly outdated
  - Nbardy/Synthetic-V5

  # HQ Design data
  - facet/facsed_pro

  # Real photos
  - Nbardy/renamed_waves
  - Nbardy/photo_geometric
  - Nbardy/light_illusion

  # Diversity data
  - facet/interesting_humans_synthetic
  - facet/generic_humans_synthetic
  - facet/unique_humans_synthetic


effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors